spring:
  application:
    name: genius
  datasource:
    url: jdbc:postgresql://localhost:15001/genius
    username: postgres
    password: secret99
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
genius:
  app:
    jwtSecret: ${GENIUS_APP_JWT_SECRET}
    jwtExpirationMs: ${GENIUS_APP_JWT_EXPIRATION_MS}
